/* Member-only group conversation and monthly session calendar. */
(() => {
 let data, user, current, month=new Date(new Date().getFullYear(),new Date().getMonth(),1), loading=false, socket, heartbeat, reconnect, pendingRefresh=false, lastMessages='';
 const dialog=document.createElement('dialog');dialog.className='group-dialog';
 dialog.innerHTML='<div class="dialog-head"><div><h2 id="groupHeading"></h2><small id="chatConnection" role="status">Connexion…</small></div><button type="button" class="icon" aria-label="Fermer le groupe">×</button></div><div class="chat-tabs"><button class="ghost active" type="button" data-chat-tab="chat">Chat</button><button class="ghost" type="button" data-chat-tab="calendar">Calendrier</button></div><div id="groupCalendar" hidden></div><section id="groupChat"><div id="groupMessages" class="messages" role="log" aria-label="Messages du groupe" aria-live="polite"></div><form id="groupMessageForm"><label class="chat-label" for="chatBody">Ton message</label><div class="chat-composer"><textarea id="chatBody" name="body" rows="2" maxlength="2000" required placeholder="Écris à ton groupe…"></textarea><button class="primary" aria-label="Envoyer le message">Envoyer ↗</button></div><small>Entrée pour envoyer · Maj + Entrée pour une nouvelle ligne</small><p id="groupMessageStatus" role="status"></p></form></section>';
 document.body.append(dialog);
 const find=id=>dialog.querySelector('#'+id);
 const esc=escapeHtml;
 const request=(path,opts)=>window.PlayLink.account.request(path,opts);
 let kind='group';
 function stopChat(){clearInterval(heartbeat);clearTimeout(reconnect);if(socket){socket.onclose=null;socket.close();socket=null;}}
 function connectChat(){
  stopChat();if(!dialog.open)return;
  const cfg=window.PLAYLINK_CONFIG, token=readSaved('playlink-session',null)?.access_token;
  if(!token)return;
  find('chatConnection').textContent='Connexion au chat…';
  const topic='realtime:'+kind+'-'+current.id;
  socket=new WebSocket(cfg.url.replace(/^http/,'ws')+'/realtime/v1/websocket?apikey='+encodeURIComponent(cfg.key)+'&vsn=1.0.0');
  const send=(event,payload,ref='1')=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({topic,event,payload,ref}));};
  socket.onopen=()=>{send('phx_join',{config:{broadcast:{self:false},presence:{key:''},postgres_changes:[{event:'INSERT',schema:'public',table:kind==='activity'?'messages':'group_messages',filter:(kind==='activity'?'event_id':'group_id')+'=eq.'+current.id}]},access_token:token});heartbeat=setInterval(()=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({topic:'phoenix',event:'heartbeat',payload:{},ref:String(Date.now())}));},25000);};
  socket.onmessage=e=>{let msg;try{msg=JSON.parse(e.data);}catch{return;}if(msg.event==='phx_reply'&&msg.ref==='1'){find('chatConnection').textContent=msg.payload.status==='ok'?'Chat en direct · réservé aux membres':'Reconnexion en cours…';if(msg.payload.status!=='ok')socket.close();}if(msg.event==='postgres_changes')messages();};
  socket.onclose=()=>{clearInterval(heartbeat);find('chatConnection').textContent='Connexion interrompue · nouvelle tentative…';if(dialog.open)reconnect=setTimeout(async()=>{await messages();connectChat();},3000);};
 }
 function tab(mode){find('groupCalendar').hidden=mode!=='calendar';find('groupChat').hidden=mode!=='chat';dialog.querySelectorAll('[data-chat-tab]').forEach(b=>b.classList.toggle('active',b.dataset.chatTab===mode));}
 dialog.addEventListener('close',stopChat);
 function calendar(){
  const year=month.getFullYear(), m=month.getMonth(), offset=(new Date(year,m,1).getDay()+6)%7, days=new Date(year,m+1,0).getDate();
  const sessions=data.events.filter(e=>e.group_id===current.id).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
  find('groupCalendar').innerHTML=`<div class="group-month"><button class="ghost" data-month="-1" aria-label="Mois précédent">←</button><h3>${esc(month.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}))}</h3><button class="ghost" data-month="1" aria-label="Mois suivant">→</button></div><div class="group-calendar">${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=>`<span class="weekday">${d}</span>`).join('')}${Array.from({length:offset},()=>'<div class="calendar-blank"></div>').join('')}${Array.from({length:days},(_,i)=>{const day=i+1, es=sessions.filter(e=>{const d=new Date(e.starts_at);return d.getFullYear()===year&&d.getMonth()===m&&d.getDate()===day;});return `<div class="calendar-day"><span>${day}</span>${es.map(e=>`<button type="button" data-session-id="${e.id}" class="calendar-session ${e.cancelled?'cancelled':''}" title="${esc(e.title)}">${esc(new Date(e.starts_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))} ${esc(e.title)}${e.cancelled?' · Annulée':''}</button>`).join('')}</div>`;}).join('')}</div><p class="muted">Clique sur une session pour voir les détails et les participants.</p>${sessions.some(e=>{const d=new Date(e.starts_at);return d.getFullYear()===year&&d.getMonth()===m;})?'':'<p>Aucune session ce mois-ci.</p>'}`;
 }
 async function messages(){
  if(!current)return;if(loading){pendingRefresh=true;return;} loading=true; const groupId=current.id;
  try{const rows=await request('/rest/v1/'+(kind==='activity'?'messages?event_id':'group_messages?group_id')+'=eq.'+groupId+'&select=*&order=created_at.desc,id.desc&limit=100');if(!dialog.open||current.id!==groupId)return;
   const list=find('groupMessages'), key=JSON.stringify(rows);if(key===lastMessages)return;const atBottom=list.scrollHeight-list.scrollTop-list.clientHeight<80||!lastMessages;lastMessages=key;
   let day='';list.innerHTML=rows.reverse().map(r=>{const d=new Date(r.created_at), label=d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}), separator=day!==label?`<div class="chat-date">${esc(label)}</div>`:'';day=label;const name=data.profiles.find(p=>p.id===r.author)?.name||'Sportif';return `${separator}<div class="chat-row ${r.author===user?'own':''}"><span class="chat-avatar">${esc(name.charAt(0))}</span><div class="chat-bubble"><strong>${r.author===user?'Toi':esc(name)}</strong><p>${esc(r.body)}</p><small>${esc(d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))}</small></div></div>`;}).join('')||'<div class="chat-empty">On en parle ici ?<p>Organise la prochaine session avec ton groupe.</p></div>';
   if(atBottom)list.scrollTop=list.scrollHeight;
  }catch(e){find('groupMessageStatus').textContent=e.message;}finally{loading=false;if(pendingRefresh){pendingRefresh=false;messages();}}
 }
 window.PlayLinkGroups={async openActivity(snapshot,uid,id){data=snapshot;user=uid;const e=data.events.find(e=>e.id===id);if(!e||!data.participations.some(p=>p.event_id===id&&p.user_id===uid&&p.status==='accepted'))return;stopChat();kind='activity';current=e;document.getElementById('eventDialog').close();find('groupHeading').textContent=e.title;dialog.querySelector('.chat-tabs').hidden=true;tab('chat');dialog.querySelector('form').reset();find('groupMessageStatus').textContent=e.cancelled?'Activité annulée : le chat est en lecture seule.':'';dialog.querySelector('form button').disabled=Boolean(e.cancelled);find('chatBody').disabled=Boolean(e.cancelled);lastMessages='';find('groupMessages').textContent='Chargement…';dialog.showModal();await messages();connectChat();},render(snapshot,uid){data=snapshot;user=uid;if(dialog.open){const g=kind==='activity'?data.events.find(e=>e.id===current?.id&&data.participations.some(p=>p.event_id===e.id&&p.user_id===user&&p.status==='accepted')):data.groups.find(g=>g.id===current?.id&&data.members.some(m=>m.group_id===g.id&&m.user_id===user));if(!g){dialog.close();return;}current=g;if(kind==='group')calendar();else{dialog.querySelector('form button').disabled=Boolean(g.cancelled);find('chatBody').disabled=Boolean(g.cancelled);}}document.querySelectorAll('#communityPanel [data-action="group_session"]').forEach(b=>{if(b.parentElement.querySelector('[data-open-group]'))return;const btn=document.createElement('button');btn.type='button';btn.className='ghost';btn.textContent='Calendrier & discussion';btn.dataset.openGroup=b.dataset.id;b.parentElement.append(btn);});}};
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-open-group]');if(!b)return;stopChat();kind='group';current=data.groups.find(g=>g.id===b.dataset.openGroup);if(!current)return;dialog.querySelector('.chat-tabs').hidden=false;dialog.querySelector('form button').disabled=false;find('chatBody').disabled=false;month=new Date(new Date().getFullYear(),new Date().getMonth(),1);find('groupHeading').textContent=current.name;find('groupMessageStatus').textContent='';dialog.querySelector('form').reset();lastMessages='';find('groupMessages').textContent='Chargement…';tab('chat');calendar();dialog.showModal();await messages();connectChat();});
 dialog.querySelector('[aria-label="Fermer le groupe"]').onclick=()=>dialog.close();
 dialog.addEventListener('click',e=>{const t=e.target.closest('[data-chat-tab]');if(t)tab(t.dataset.chatTab);const nav=e.target.closest('[data-month]');if(nav){month=new Date(month.getFullYear(),month.getMonth()+Number(nav.dataset.month),1);calendar();}const s=e.target.closest('[data-session-id]');if(s){dialog.close();window.PlayLink.openDetail(s.dataset.sessionId);}});
 find('chatBody').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();const btn=dialog.querySelector('form button');if(!btn.disabled&&e.target.value.trim())dialog.querySelector('form').requestSubmit(btn);}});
 dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter,body=new FormData(e.target).get('body')?.trim();if(!body||kind==='activity'&&current.cancelled)return;btn.disabled=true;try{await request(kind==='activity'?'/rest/v1/rpc/playlink_action':'/rest/v1/group_messages',{method:'POST',body:JSON.stringify(kind==='activity'?{action:'message',data:{event_id:current.id,body}}:{group_id:current.id,author:user,body})});e.target.reset();await messages();find('groupMessageStatus').textContent='Message envoyé.';}catch(error){find('groupMessageStatus').textContent=error.message;}finally{btn.disabled=kind==='activity'&&Boolean(current.cancelled);}});
 setInterval(()=>{if(dialog.open&&!document.hidden)messages();},15000);
})();
