import React,{useState,useRef,useEffect} from 'react';
import {View,Text,TextInput,Pressable} from 'react-native';
export default function AddressSearch({value,onChange,onSelect}){
 const [items,setItems]=useState([]),[status,setStatus]=useState('Recherche d’adresses et de lieux en France · IGN');
 const timer=useRef(),controller=useRef(),revision=useRef(0);
 useEffect(()=>()=>{clearTimeout(timer.current);controller.current?.abort();},[]);
 function change(text){onChange(text);clearTimeout(timer.current);controller.current?.abort();const ticket=++revision.current;setItems([]);if(text.trim().length<3){setStatus('Saisis au moins 3 caractères.');return;}timer.current=setTimeout(async()=>{controller.current=new AbortController();const signal=controller.current.signal;const timeout=setTimeout(()=>controller.current?.signal===signal&&controller.current.abort(),8000);try{setStatus('Recherche…');const response=await fetch('https://data.geopf.fr/geocodage/completion/?text='+encodeURIComponent(text)+'&type=StreetAddress,PositionOfInterest&maximumResponses=6',{signal});if(!response.ok)throw new Error();const data=await response.json();if(ticket!==revision.current)return;const found=(data.results||[]).filter(r=>typeof r.fulltext==='string'&&Number.isFinite(r.x)&&Number.isFinite(r.y)&&Math.abs(r.x)<=180&&Math.abs(r.y)<=90);setItems(found);setStatus(found.length?'Choisis une adresse.':'Précise l’adresse ou place le point directement sur la carte.');}catch{if(ticket===revision.current)setStatus('Suggestions indisponibles. Saisis l’adresse et place le point sur la carte.');}finally{clearTimeout(timeout);}},350);}
 return <View style={{marginVertical:10}}><Text>Adresse</Text><TextInput accessibilityLabel="Adresse" value={value} onChangeText={change} maxLength={200} placeholder="Adresse ou nom du terrain" style={{padding:13,borderWidth:1,borderColor:'#dce6de',backgroundColor:'#f5f8f2',fontSize:16,marginTop:6,borderRadius:5}}/>{items.map((item,i)=><Pressable accessibilityRole="button" key={i} style={{padding:12,borderBottomWidth:1,borderColor:'#d8dece'}} onPress={()=>{revision.current++;controller.current?.abort();setItems([]);setStatus('Adresse sélectionnée. Ajuste le point si nécessaire.');onSelect(item);}}><Text>{item.fulltext}</Text></Pressable>)}<Text style={{color:'#62715e',marginTop:5}}>{status}</Text></View>;
}
