import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as api from './api';
const green='#6c9e86',ink='#244e40',lemon='#e1f38b';
const dayKey=d=>`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
export function SessionCalendar({events,onOpen}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selected,setSelected]=useState(null);
 const start=(new Date(month.getFullYear(),month.getMonth(),1).getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const cells=Array.from({length:Math.ceil((start+days)/7)*7},(_,i)=>i-start+1);
 const current=events.filter(e=>{const d=new Date(e.starts_at);return d.getMonth()===month.getMonth()&&d.getFullYear()===month.getFullYear()&&(!selected||dayKey(d)===selected);}).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
 function move(n){setSelected(null);setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));}
 return <View><View style={c.row}><Pressable accessibilityRole="button" accessibilityLabel="Mois précédent" onPress={()=>move(-1)} style={c.control}><Text>←</Text></Pressable><Text style={c.month}>{month.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</Text><Pressable accessibilityRole="button" accessibilityLabel="Mois suivant" onPress={()=>move(1)} style={c.control}><Text>→</Text></Pressable></View><Pressable onPress={()=>{setSelected(null);setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1));}}><Text style={c.link}>Aujourd’hui · Voir tout le mois</Text></Pressable><View style={c.grid}>{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(x=><Text key={x} style={c.week}>{x}</Text>)}{cells.map((day,i)=>{if(day<1||day>days)return <View key={i} style={c.day}/>;const d=new Date(month.getFullYear(),month.getMonth(),day),key=dayKey(d),count=events.filter(e=>dayKey(new Date(e.starts_at))===key).length;return <Pressable key={i} accessibilityRole="button" accessibilityLabel={`${d.toLocaleDateString('fr-FR')}, ${count} activités`} onPress={()=>setSelected(selected===key?null:key)} style={[c.day,selected===key&&c.selected,dayKey(new Date())===key&&c.today]}><Text style={c.number}>{day}</Text>{count>0&&<Text style={c.count}>{count} ●</Text>}</Pressable>;})}</View>{current.length?current.map(e=><Pressable key={e.id} onPress={()=>onOpen(e.id)} style={c.event}><Text style={c.eventTitle}>{e.title}</Text><Text style={c.info}>{new Date(e.starts_at).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · {e.sport}{e.cancelled?' · Annulée':''}</Text></Pressable>):<Text style={c.info}>Aucune activité pour cette période.</Text>}</View>;
}
export function LiveChat({kind,id,profiles,cancelled=false}){
 const [messages,setMessages]=useState([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[status,setStatus]=useState('Connexion…');
 const list=useRef(),atBottom=useRef(true),active=useRef(true),loading=useRef(false),user=api.currentUser()?.id;
 useEffect(()=>{
  active.current=true;let live=true,stop;
  async function load(){if(loading.current)return;loading.current=true;try{const rows=await api.chatMessages(kind,id);if(live){setMessages(rows.reverse());setError('');}}catch(e){if(live)setError(e.message);}finally{loading.current=false;}}
  load().then(()=>{if(live)stop=api.subscribeChat(kind,id,load,s=>{if(live)setStatus(s);});});
  const poll=setInterval(()=>{if(AppState.currentState==='active')load();},15000),sub=AppState.addEventListener('change',s=>{if(s==='active')load();});
  return()=>{live=false;active.current=false;stop?.();clearInterval(poll);sub.remove();};
 },[kind,id]);
 async function send(){const body=draft.trim();if(!body||sending||cancelled)return;setSending(true);try{await api.sendChat(kind,id,body);const rows=await api.chatMessages(kind,id);if(active.current){setDraft('');atBottom.current=true;setMessages(rows.reverse());setError('');}}catch(e){if(active.current)setError(e.message);}finally{if(active.current)setSending(false);}}
 return <View style={{flex:1}}><Text style={c.info}>{status} · Réservé aux membres</Text><ScrollView ref={list} style={{flex:1}} contentContainerStyle={{paddingVertical:8}} keyboardShouldPersistTaps="handled" onScroll={e=>{const {layoutMeasurement,contentOffset,contentSize}=e.nativeEvent;atBottom.current=layoutMeasurement.height+contentOffset.y>=contentSize.height-70;}} scrollEventThrottle={100} onContentSizeChange={()=>{if(atBottom.current)list.current?.scrollToEnd({animated:true});}}>{!messages.length&&<Text style={c.info}>Écris le premier message.</Text>}{messages.map(m=><View key={m.id} style={[c.bubble,m.author===user?c.mine:c.other]}><Text style={c.author}>{profiles.find(p=>p.id===m.author)?.name||'Sportif'} · {new Date(m.created_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</Text><Text style={c.body}>{m.body}</Text><Text style={c.date}>{new Date(m.created_at).toLocaleDateString('fr-FR')}</Text></View>)}</ScrollView>{error?<Text accessibilityRole="alert" style={{color:'#9c352e'}}>{error}</Text>:null}{cancelled?<Text style={c.info}>Activité annulée : discussion en lecture seule.</Text>:<View style={c.composer}><TextInput accessibilityLabel="Ton message" placeholder="Ton message…" multiline maxLength={2000} value={draft} onChangeText={setDraft} style={c.input}/><Pressable accessibilityRole="button" accessibilityLabel="Envoyer le message" disabled={sending||!draft.trim()} onPress={send} style={[c.send,(!draft.trim()||sending)&&{opacity:.45}]}>{sending?<ActivityIndicator color={ink}/>:<Text style={{color:ink,fontWeight:'700'}}>Envoyer</Text>}</Pressable></View>}</View>;
}
const c=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},control:{padding:14},month:{fontSize:18,fontWeight:'700',color:ink},link:{color:ink,marginVertical:10},grid:{flexDirection:'row',flexWrap:'wrap',marginBottom:12},week:{width:'14.2857%',textAlign:'center',fontSize:11,color:ink,paddingVertical:8},day:{width:'14.2857%',height:55,borderWidth:.5,borderColor:'#dbe5de',alignItems:'center',paddingTop:7},selected:{backgroundColor:lemon},today:{borderColor:green,borderWidth:2},number:{color:ink},count:{fontSize:10,color:ink,marginTop:3},event:{padding:10,borderBottomWidth:1,borderColor:'#dbe5de'},eventTitle:{fontWeight:'700',color:ink},info:{fontSize:12,color:'#62715e',marginVertical:6},bubble:{maxWidth:'88%',paddingVertical:3,paddingHorizontal:6,borderRadius:7,marginVertical:3},mine:{alignSelf:'flex-end',backgroundColor:lemon},other:{alignSelf:'flex-start',backgroundColor:'#f1f5ef'},author:{fontSize:10,color:ink},body:{fontSize:12,lineHeight:16,color:ink,marginVertical:1},date:{fontSize:9,color:'#62715e',textAlign:'right'},composer:{flexDirection:'row',gap:8,paddingVertical:8,alignItems:'flex-end'},input:{flex:1,borderWidth:1,borderColor:'#cedbd1',padding:8,maxHeight:110,minHeight:40,color:ink},send:{padding:12,backgroundColor:lemon,borderRadius:3}});
