import React,{useEffect,useState} from 'react';
import {Modal,Text,ScrollView,Pressable,TextInput,View,Alert,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import DateTimePicker from '@react-native-community/datetimepicker';
import AddressSearch from './AddressSearch';
export default function EditEventSheet({event,onClose,onSave,busy,MapPanel}){
 const [draft,setDraft]=useState(null),[picker,setPicker]=useState(null);
 useEffect(()=>{if(event)setDraft({...event,date:new Date(event.starts_at),point:{lat:event.lat,lng:event.lng},capacity:String(event.capacity)});setPicker(null);},[event]);
 const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const button=(title,onPress)=><Pressable accessibilityRole="button" disabled={busy} onPress={onPress} style={{padding:14,borderWidth:1,borderColor:'#aebaa6',borderRadius:3,marginVertical:6}}><Text style={{color:'#244e40',fontWeight:'600'}}>{title}</Text></Pressable>;
 const field=(key,label,max=100)=><View style={{marginVertical:10}}><Text>{label}</Text><TextInput accessibilityLabel={label} value={draft[key]} maxLength={max} keyboardType={key==='capacity'?'number-pad':'default'} multiline={key==='description'} onChangeText={v=>update(key,v)} style={{padding:13,borderWidth:1,borderColor:'#dce6de',backgroundColor:'#f5f8f2',borderRadius:5,fontSize:16}}/></View>;
 function save(){const capacity=Number(draft.capacity);if(!draft.point||draft.title.trim().length<3||draft.location.trim().length<2||!draft.city.trim()||draft.date<=new Date()||!Number.isInteger(capacity)||capacity<2||capacity>200){Alert.alert('Vérifie le rendez-vous','Choisis une adresse, un point, une date future et 2 à 200 places.');return;}onSave({...draft,event_id:event.id,starts_at:draft.date.toISOString(),lat:draft.point.lat,lng:draft.point.lng,capacity});}
 return <Modal visible={!!event} onRequestClose={onClose} animationType="slide"><SafeAreaView style={{flex:1,backgroundColor:'#f7f5ed'}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20}}><Text style={{fontSize:25,color:'#244e40',fontWeight:'700'}}>Modifier le rendez-vous</Text>{button('Fermer',onClose)}{draft&&<>{field('title','Titre',120)}{button(draft.date.toLocaleDateString('fr-FR'),()=>setPicker('date'))}{button(draft.date.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),()=>setPicker('time'))}{picker&&<><DateTimePicker value={draft.date} mode={picker} is24Hour onChange={(e,date)=>{if(Platform.OS==='android')setPicker(null);if(date)update('date',date);}}/>{Platform.OS==='ios'&&button('Valider',()=>setPicker(null))}</>}{field('city','Ville')}<AddressSearch value={draft.location} onChange={v=>setDraft(d=>({...d,location:v,point:null}))} onSelect={a=>setDraft(d=>({...d,location:a.fulltext,city:a.city||d.city,point:{lat:a.y,lng:a.x}}))}/><MapPanel pick point={draft.point} onPoint={v=>update('point',v)}/>{field('capacity','Nombre de places')}{field('description','Description',2000)}<Text>Le sport et les règles d’accès sont conservés. Les participants seront prévenus des modifications.</Text>{button('Enregistrer les modifications',save)}</>}</ScrollView></SafeAreaView></Modal>;
}
