import React from 'react';
import {View,Text,Image,Pressable,TextInput,Alert,Linking,StyleSheet} from 'react-native';
import {Picker} from '@react-native-picker/picker';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
const LEVELS=['Non renseigné','Débutant','Intermédiaire','Confirmé','Compétition'];
const DIVISIONS=['Basket','Beach-volley','Football','Five','Volley-ball','Rugby'];
const extra=sport=>sport==='Athlétisme'?['pace','Allure fondamentale (min/km)']:['Tennis','Badminton'].includes(sport)?['ranking','Classement']:DIVISIONS.includes(sport)?['division','Division']:null;
export default function ProfileEditor({value,onChange,onSave,onLogout,onDelete,busy,sports}){
 const change=(key,v)=>onChange({...value,[key]:v});
 const button=(title,action)=> <Pressable disabled={busy} accessibilityRole="button" style={s.button} onPress={action}><Text style={s.buttonText}>{title}</Text></Pressable>;
 const field=(label,key,max=100)=> <View style={s.field}><Text>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value[key]||''} maxLength={max} onChangeText={v=>change(key,v)}/></View>;
 async function photo(){try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:1});if(result.canceled)return;const image=await ImageManipulator.manipulateAsync(result.assets[0].uri,[{resize:{width:192,height:192}}],{compress:.65,format:ImageManipulator.SaveFormat.JPEG,base64:true});const avatar='data:image/jpeg;base64,'+image.base64;if(avatar.length>60000)throw new Error('Choisis une photo moins détaillée.');change('avatar',avatar);}catch(e){Alert.alert('Photo',e.message);}}
 return <><Text style={s.heading}>Mon profil sportif</Text>{value.avatar?<Image accessibilityLabel="Photo de profil" source={{uri:value.avatar}} style={{width:80,height:80,borderRadius:40}}/>:null}{button('Choisir une photo',photo)}{value.avatar?button('Retirer la photo',()=>change('avatar','')):null}{field('Prénom ou pseudo','name',60)}{field('Ville','city')}
 <Text style={s.heading}>Mes sports</Text><Text>Sélectionne les sports que tu pratiques, puis renseigne ton niveau si tu le souhaites.</Text>
 <Picker accessibilityLabel="Ajouter un sport" selectedValue="" onValueChange={sport=>{if(sport)change('sports',{...value.sports,[sport]:'Non renseigné'});}}><Picker.Item label="Ajouter un sport…" value=""/>{sports.filter(sport=>!Object.hasOwn(value.sports||{},sport)).map(sport=><Picker.Item key={sport} label={sport} value={sport}/>)}</Picker>
 {Object.entries(value.sports||{}).map(([sport,level])=>{const info=extra(sport);return <View key={sport} style={s.card}><Text style={s.heading}>{sport}</Text><Text>Niveau</Text><Picker accessibilityLabel={sport+' : niveau'} selectedValue={level} onValueChange={v=>change('sports',{...value.sports,[sport]:v})}>{LEVELS.map(v=><Picker.Item key={v} value={v} label={v||'Non renseigné'}/>)}</Picker>{info?<><Text>{info[1]}</Text><TextInput accessibilityLabel={sport+' : '+info[1]} style={s.input} maxLength={100} value={value.sport_details?.[sport]?.[info[0]]||''} onChangeText={v=>change('sport_details',{...value.sport_details,[sport]:{...value.sport_details?.[sport],[info[0]]:v}})}/></>:null}{button('Retirer '+sport,()=>{const next={...value.sports},details={...value.sport_details};delete next[sport];delete details[sport];onChange({...value,sports:next,sport_details:details});})}</View>;})}
 {field('Quelques mots sur toi','bio',1000)}{button('Enregistrer',()=>onSave(value))}{button('Confidentialité',()=>Linking.openURL('https://playlink-mvp.vercel.app/privacy.html'))}{button('Conditions d’utilisation',()=>Linking.openURL('https://playlink-mvp.vercel.app/terms.html'))}{button('Supprimer mon compte',()=>Alert.alert('Supprimer définitivement le compte ?','Ton profil, tes messages et tes événements seront supprimés. Les participants seront prévenus. Cette action est irréversible.',[{text:'Retour',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:onDelete}]))}{button('Se déconnecter',onLogout)}</>;
}
const s=StyleSheet.create({heading:{fontSize:21,fontWeight:'700',color:'#174c3e',marginVertical:14},field:{marginVertical:9},input:{padding:13,backgroundColor:'#fffef9',borderWidth:1,borderColor:'#c7d0bd',borderRadius:5,fontSize:16,marginTop:6},card:{padding:16,marginVertical:10,backgroundColor:'#fffef9',borderWidth:1,borderColor:'#c7d0bd',borderRadius:8},button:{padding:14,borderWidth:1,borderColor:'#aebaa6',borderRadius:6,marginVertical:6},buttonText:{color:'#174c3e',fontWeight:'600',textAlign:'center'}});
